# Generated by Django 6.0.8 on 2026-08-05 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_block_reason_customer_city_and_more'),
        ('inventory', '0001_initial'),
        ('rentals', '0004_rental_delivery_lat_rental_delivery_lng'),
        ('tenants', '0002_tenant_evolution_api_key_tenant_evolution_api_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue_rental', 'Locação Atrasada'), ('equipment_maintenance', 'Equipamento em Manutenção há muito tempo'), ('low_available', 'Poucos Equipamentos Disponíveis'), ('payment_overdue', 'Pagamento Pendente'), ('high_expense', 'Despesa Alta no Mês'), ('customer_blocked', 'Cliente Bloqueado Tentou Locar'), ('system_error', 'Erro Crítico no Sistema'), ('whatsapp_down', 'WhatsApp Desconectado')], max_length=30, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Alerta'), ('info', 'Informativo')], max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('unread', 'Não Lida'), ('read', 'Lida'), ('dismissed', 'Dispensada')], default='unread', max_length=10, verbose_name='Status')),
                ('whatsapp_sent', models.BooleanField(default=False, verbose_name='WhatsApp Enviado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('related_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipment')),
                ('related_rental', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.rental')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('overdue_rental', 'Locação Atrasada'), ('equipment_maintenance', 'Equipamento em Manutenção há muito tempo'), ('low_available', 'Poucos Equipamentos Disponíveis'), ('payment_overdue', 'Pagamento Pendente'), ('high_expense', 'Despesa Alta no Mês'), ('customer_blocked', 'Cliente Bloqueado Tentou Locar'), ('system_error', 'Erro Crítico no Sistema'), ('whatsapp_down', 'WhatsApp Desconectado')], max_length=30, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('critical', 'Crítico'), ('warning', 'Alerta'), ('info', 'Informativo')], default='warning', max_length=10, verbose_name='Severidade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notify_channel', models.CharField(choices=[('system', 'Apenas no Sistema'), ('whatsapp', 'WhatsApp do Admin'), ('both', 'Sistema + WhatsApp')], default='system', max_length=10, verbose_name='Canal de Notificação')),
                ('threshold', models.IntegerField(default=0, help_text='Ex: dias de atraso, qtd mínima disponível, valor máximo', verbose_name='Limite/Threshold')),
                ('notify_phone', models.CharField(blank=True, help_text='Número do admin para receber alertas críticos', max_length=20, verbose_name='WhatsApp para Notificar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Regra de Alerta',
                'verbose_name_plural': 'Regras de Alerta',
                'ordering': ['alert_type'],
                'unique_together': {('tenant', 'alert_type')},
            },
        ),
    ]
