# Generated by Django 6.0.8 on 2026-08-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço de Entrega'),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável no Local'),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável'),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ponto de Referência'),
        ),
    ]
