# Generated by Django 6.0.8 on 2026-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_rental_delivery_address_rental_delivery_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='rental',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Pagamento'),
        ),
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'À Vista (Dinheiro)'), ('pix', 'PIX'), ('credit_card', 'Cartão de Crédito'), ('debit_card', 'Cartão de Débito'), ('later', 'A Receber (Depois)'), ('transfer', 'Transferência Bancária')], default='later', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
