# Generated by Django 6.0.8 on 2026-08-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_rental_delivery_lat_rental_delivery_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Distância (km)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_time_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo estimado (min)'),
        ),
    ]
