# Generated by Django 6.0.8 on 2026-08-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='block_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Motivo do Bloqueio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='customer',
            name='complement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Crédito'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço de Entrega/Obra'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade (entrega)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro (entrega)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número (entrega)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência/Ponto de Referência'),
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF (entrega)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Cliente com pendências ou inadimplente', verbose_name='Bloqueado'),
        ),
        migrations.AddField(
            model_name='customer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='customer',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, help_text='Ex: À vista, 30 dias, 7/14/21 dias', max_length=100, verbose_name='Condição de Pagamento'),
        ),
        migrations.AddField(
            model_name='customer',
            name='person_type',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone 2'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference1_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência 1 - Nome'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference1_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referência 1 - Telefone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference2_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Referência 2 - Nome'),
        ),
        migrations.AddField(
            model_name='customer',
            name='reference2_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referência 2 - Telefone'),
        ),
        migrations.AddField(
            model_name='customer',
            name='rg',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG / Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável na Obra'),
        ),
        migrations.AddField(
            model_name='customer',
            name='site_contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome / Razão Social'),
        ),
    ]
