# Generated by Django 6.0.8 on 2026-08-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Pago'), ('pending', 'A Receber'), ('overdue', 'Atrasado'), ('cancelled', 'Cancelado')], default='paid', max_length=10, verbose_name='Status do Pagamento'),
        ),
    ]
