# Generated by Django 6.0.8 on 2026-08-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/pdfs/', verbose_name='Arquivo PDF')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rentals.rental')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-generated_at'],
            },
        ),
    ]
