# Generated by Django 6.0.8 on 2026-08-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('document', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/', verbose_name='Logo')),
                ('contract_clauses', models.TextField(blank=True, verbose_name='Cláusulas do Contrato')),
                ('return_conditions', models.TextField(blank=True, verbose_name='Condições de Devolução')),
                ('penalty_terms', models.TextField(blank=True, verbose_name='Termos de Multa')),
                ('evolution_instance', models.CharField(blank=True, max_length=100, verbose_name='Instância Evolution')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
    ]
