# Generated by Django 6.0.8 on 2026-08-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='evolution_api_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='Evolution API Key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='evolution_api_url',
            field=models.CharField(blank=True, help_text='Ex: http://localhost:8080 ou https://evolution.seudominio.com', max_length=300, verbose_name='Evolution API URL'),
        ),
    ]
