# Generated by Django 6.0.8 on 2026-08-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_evolution_api_key_tenant_evolution_api_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='landing_color',
            field=models.CharField(blank=True, default='#2563eb', help_text='Cor em hex. Ex: #2563eb (azul), #f59e0b (laranja)', max_length=7, verbose_name='Cor principal'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_description',
            field=models.TextField(blank=True, help_text='Texto do hero da landing page', verbose_name='Descrição da Landing'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_headline',
            field=models.CharField(blank=True, help_text='Ex: Locação de Máquinas para Construção Civil', max_length=200, verbose_name='Título da Landing'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='landing_whatsapp',
            field=models.CharField(blank=True, help_text='Número para botão WhatsApp na landing. Ex: 5534988267096', max_length=20, verbose_name='WhatsApp (landing)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL da landing page: locamaq.com/site/sua-slug', null=True, unique=True, verbose_name='Slug (URL)'),
        ),
    ]
