# Generated by Django 6.0.8 on 2026-08-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='send_log',
            field=models.TextField(blank=True, help_text='Log detalhado de cada tentativa de envio', verbose_name='Relatório de Envio'),
        ),
    ]
