# Generated by Django 6.0.8 on 2026-08-05 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código Patrimônio')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('category', models.CharField(choices=[('scaffolding', 'Andaime'), ('mixer', 'Betoneira'), ('compactor', 'Compactador'), ('generator', 'Gerador'), ('pump', 'Bomba'), ('other', 'Outros')], default='other', max_length=30, verbose_name='Categoria')),
                ('state', models.CharField(choices=[('available', 'Disponível'), ('rented', 'Locado'), ('maintenance', 'Em Manutenção'), ('retired', 'Baixado')], default='available', max_length=20, verbose_name='Estado')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Diária')),
                ('weekly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Semanal')),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Mensal')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipments/', verbose_name='Imagem')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EquipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(choices=[('available', 'Disponível'), ('rented', 'Locado'), ('maintenance', 'Em Manutenção'), ('retired', 'Baixado')], max_length=20, verbose_name='Estado Anterior')),
                ('new_state', models.CharField(choices=[('available', 'Disponível'), ('rented', 'Locado'), ('maintenance', 'Em Manutenção'), ('retired', 'Baixado')], max_length=20, verbose_name='Novo Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.equipment')),
            ],
            options={
                'verbose_name': 'Histórico do Equipamento',
                'verbose_name_plural': 'Histórico dos Equipamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
